
package pasaud.voip.protocol.tcp;

public enum TCPHeaderType {
    ADDPLAYER, ADDGROUP, ADDPLAYERTOGROUP, GETPLAYERINFO, FORCESETPLAYERINFO, DISCONNECTPLAYER, BANPLAYER, MUTEPLAYER, SENDAUDIOTOGROUP;
}
