
package pasaud.voip.protocol.tcp.gameservertoserver;

public enum Headers {
    ADDPLAYER, ADDGROUP, ADDPLAYERTOGROUP, GETPLAYERINFO, FORCESETPLAYERINFO, DISCONNECTPLAYER, BANPLAYER, MUTEPLAYER, SENDAUDIOTOGROUP;
}
